language: node_js
node_js: '8'
branches:
  only:
  - master
  - /^greenkeeper/.*$/
script:
  - npm run lint
  - npm run test
  - npm run generate
after_script:
  - npm install -g codecov
  - codecov
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: dist
  verbose: true
  on:
    branch: master
